# Generated by Django 3.1.5 on 2021-01-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0003_auto_20210119_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
